wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1675854241.803502
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 16
      - 23
      - 24
      4: 3.10.9
      5: 0.13.10
      8:
      - 5
